```{r, message=FALSE}
#load packages
library(readr)
library(dplyr)
library(stringr)
```

```{r, message=FALSE}
#load data
cbdata <- read_csv("ChatterBabyData.csv")
```

```{r}
mean(cbdata$risk_score_ASD)
var(cbdata$risk_score_ASD)
hist(cbdata$risk_score_ASD)
```
# Dealing with NAs
Cleaning NA's to 0's: 

```{r}
which(colnames(cbdata) == "mat_dep"):which(colnames(cbdata) == "momfever")
cbdata[,c(109:116)][is.na(cbdata[,c(109:116)])] <- 0

cbdata$art[is.na(cbdata$art)] <- 0  
cbdata$mom_trauma[is.na(cbdata$mom_trauma)] <- 0 
cbdata$asd_genetic[is.na(cbdata$asd_genetic)] <- 0 

#fix some NA's in totalpregnancies by setting to number of live births
cbdata$totalpregnancies[which(is.na(cbdata$totalpregnancies) == TRUE & is.na(cbdata$momlivebirths) == FALSE)] <- 
cbdata$momlivebirths[which(is.na(cbdata$totalpregnancies) == TRUE & is.na(cbdata$momlivebirths) == FALSE)]

#fix some NA's in totalpregnancies by setting to 1 if no siblings and not adopted
cbdata$totalpregnancies[which(is.na(cbdata$totalpregnancies) == TRUE & cbdata$birthordertotal == 0 & cbdata$adoption == 0)] <- 1

# set live births to number of total pregnancies 
# if number of total pregnancies = number of total siblings + 1(baby)
# so as to not include miscarriages
cbdata$momlivebirths[which((is.na(cbdata$momlivebirths) == TRUE) &
                           (cbdata$totalpregnancies == (cbdata$birthordertotal + 1)))] <-
  cbdata$totalpregnancies[which((is.na(cbdata$momlivebirths) == TRUE) & 
                                (cbdata$totalpregnancies == (cbdata$birthordertotal + 1)))]

# set live births to number of total pregnancies 
# if number of total pregnancies = number of full siblings + 1(baby) 
# so as to not include miscarriages (where birthordertotal = 0 because of NA in olderhalfsiblings)
cbdata$momlivebirths[which((is.na(cbdata$momlivebirths) == TRUE) &
                           (cbdata$totalpregnancies == (cbdata$numberfullsiblings + 1)))] <-
  cbdata$totalpregnancies[which((is.na(cbdata$momlivebirths) == TRUE) & 
                                (cbdata$totalpregnancies == (cbdata$numberfullsiblings + 1)))]

# set live births to number of full siblings + 1
# if number of total pregnancies > number of full siblings and 
# number of older half siblings = 0 so as to not include children only from father and miscarriages
cbdata$momlivebirths[which((is.na(cbdata$momlivebirths) == TRUE) & 
                           (cbdata$totalpregnancies > cbdata$numberfullsiblings) &
                           cbdata$olderhalfsiblings == 0 )] <-
  cbdata$numberfullsiblings[which((is.na(cbdata$momlivebirths) == TRUE) & 
                                  (cbdata$totalpregnancies > cbdata$numberfullsiblings) &
                                  cbdata$olderhalfsiblings == 0 )] + 1
```

# Cleaning `maternalpregnancyproblems_other`
```{r}
# classify as post partum psychosis
cbdata <- cbdata %>% mutate(maternalpregnancyproblems___20 = replace(maternalpregnancyproblems___20, maternalpregnancyproblems_other == "post partum anxiety" | maternalpregnancyproblems_other == "Post partum anxiety" | maternalpregnancyproblems_other == "Post-partum anxiety" | maternalpregnancyproblems_other == "Postpartum hemorrhaging" | maternalpregnancyproblems_other == "Perinatal anxiety",1))
cbdata <- cbdata %>% mutate(maternalpregnancyproblems_other = replace(maternalpregnancyproblems_other, maternalpregnancyproblems_other == "post partum anxiety" | maternalpregnancyproblems_other == "Post partum anxiety" | maternalpregnancyproblems_other == "Post-partum anxiety" | maternalpregnancyproblems_other == "Postpartum hemorrhaging" | maternalpregnancyproblems_other == "Perinatal anxiety", NA ))

# classify as Chorioamnionitis 
cbdata <- cbdata %>% mutate(maternalpregnancyproblems___21 = replace(maternalpregnancyproblems___21, maternalpregnancyproblems_other == "Chorioamnionitis", 1))
cbdata <- cbdata %>% mutate(maternalpregnancyproblems_other = replace(maternalpregnancyproblems_other, maternalpregnancyproblems_other == "Chorioamnionitis", NA))

# classify as bleeding
cbdata <- cbdata %>% mutate(maternalpregnancyproblems___14 = replace(maternalpregnancyproblems___14, maternalpregnancyproblems_other == "Unusual pain in the abdomen, stress, miscarriage probability, bleeding.", 1))
cbdata <- cbdata %>% mutate(maternalpregnancyproblems_other = replace(maternalpregnancyproblems_other, maternalpregnancyproblems_other == "Unusual pain in the abdomen, stress, miscarriage probability, bleeding.", NA))

# classify as preterm labor
cbdata <- cbdata %>% mutate(maternalpregnancyproblems___11 = replace(maternalpregnancyproblems___11, maternalpregnancyproblems_other == "Early contractions with diction starting at 30 weeks. I received steroid shot to develop baby's lungs faster.", 1))
cbdata <- cbdata %>% mutate(maternalpregnancyproblems_other = replace(maternalpregnancyproblems_other, maternalpregnancyproblems_other == "Early contractions with diction starting at 30 weeks. I received steroid shot to develop baby's lungs faster.", NA))

# classify as History of recurrent miscarriage/ recurrent pregnancy loss 
cbdata <- cbdata %>% mutate(maternalpregnancyproblems___10 = replace(maternalpregnancyproblems___10, maternalpregnancyproblems_other == "Prior full term stillbirth; had double nuchal cord resulting in emergent csection at 36 weeks", 1))
cbdata <- cbdata %>% mutate(maternalpregnancyproblems_other = replace(maternalpregnancyproblems_other, maternalpregnancyproblems_other == "Prior full term stillbirth; had double nuchal cord resulting in emergent csection at 36 weeks", NA))

# classify as hypertension
cbdata <- cbdata %>% mutate(maternalpregnancyproblems___9 = replace(maternalpregnancyproblems___9, maternalpregnancyproblems_other == "Protein in urine day of induction and hypertension only at 38 weeks" | maternalpregnancyproblems_other == "Mild hypertension at 37 weeks", 1))
cbdata <- cbdata %>% mutate(maternalpregnancyproblems_other = replace(maternalpregnancyproblems_other, maternalpregnancyproblems_other == "Protein in urine day of induction and hypertension only at 38 weeks"| maternalpregnancyproblems_other == "Mild hypertension at 37 weeks", 1))

# classify as 13, Placental abruption
cbdata <- cbdata %>% mutate(maternalpregnancyproblems___13 = replace(maternalpregnancyproblems___13, maternalpregnancyproblems_other == "Calcified placenta" | maternalpregnancyproblems_other == "Placenta calcification" | maternalpregnancyproblems_other == "Placenta hematoma" | maternalpregnancyproblems_other == "placental aging" | maternalpregnancyproblems_other == "Underperfusion placenta" , 1))
cbdata <- cbdata %>% mutate(maternalpregnancyproblems_other = replace(maternalpregnancyproblems_other, maternalpregnancyproblems_other == "Calcified placenta" | maternalpregnancyproblems_other == "Placenta calcification" | maternalpregnancyproblems_other == "Placenta hematoma" | maternalpregnancyproblems_other == "placental aging"| maternalpregnancyproblems_other == "Underperfusion placenta", NA))

# Get rid of the column 
cbdata$maternalpregnancyproblems_other <- NULL
```

# Cleaning `mom_trauma`
```{r}
# Convert all Mom Trauma NA's to 0: 
cbdata$mom_trauma[is.na(cbdata$mom_trauma)] <- 0 
```

# Cleaning `mat_mental_health_other`

```{r}
# Getting rid of column
cbdata$mat_mental_health_other = NULL
# Cleaning that can be put into other columns
cbdata[c(216, 520, 598, 1089),115] = 1
cbdata[240,83] = 1
cbdata[499,85] = 1
cbdata[c(1683, 2245), 111] = 1

# Multiple entries for one person
cbdata[912, c(227, 232)] = 1
cbdata[915, c(228, 231, 232)] = 1
cbdata[1667, c(112, 231)] = 1
cbdata[2579, c(112, 113, 230, 231)] = 1
cbdata[c(76, 2501), c(111, 112)] = 1
```

```{r}
# Cutting off Baby Age at 5 years old
cbdata$babyage = ifelse(cbdata$babyage <= 1825, cbdata$babyage, NA)
```

```{r}
predata <- cbdata %>% select(babyage, momsdeliveryage, momsedu, sex, art, artmethod___1,
                          artmethod___7, artmethod___6, artmethod___2, artmethod___3,
                          artmethod___4, artmethod___5, mom_trauma,
                          maternalpregnancyproblems___1, maternalpregnancyproblems___2,
                          maternalpregnancyproblems___3, maternalpregnancyproblems___15,
                          maternalpregnancyproblems___21, maternalpregnancyproblems___16,
                          maternalpregnancyproblems___4, maternalpregnancyproblems___5,
                          maternalpregnancyproblems___6, maternalpregnancyproblems___7,
                          maternalpregnancyproblems___8, maternalpregnancyproblems___9,
                          maternalpregnancyproblems___10, maternalpregnancyproblems___11,
                          maternalpregnancyproblems___12, maternalpregnancyproblems___13,
                          maternalpregnancyproblems___14, maternalpregnancyproblems___17,
                          maternalpregnancyproblems___19, maternalpregnancyproblems___20,
                          maternalpregnancyproblems___18,
                          matmentalhealth___1, matmentalhealth___2, matmentalhealth___3,
                          matmentalhealth___4, matmentalhealth___5, matmentalhealth___6,
                          matmentalhealth___7, mat_dep, mat_anx,
                          mat_ocd, mat_bp, mat_adhd, mat_pssd, momfever, whenfever___1,
                          whenfever___2, whenfever___3, tobacco_pregnancy_when___1,
                          tobacco_pregnancy_when___2, tobacco_pregnancy_when___3,
                          vaping_pregnancy___1, vaping_pregnancy___2, vaping_pregnancy___3,
                          alcohol_pregnancy_when___1, alcohol_pregnancy_when___2,
                          alcohol_pregnancy_when___3, cannabis_pregnancy_when___1,
                          cannabis_pregnancy_when___2, cannabis_pregnancy_when___3,
                          stimulants_pregnancy_when___1, stimulants_pregnancy_when___2,
                          stimulants_pregnancy_when___3, opioids_pregnancy_when___1,
                          opioids_pregnancy_when___2, opioids_pregnancy_when___3,
                          psychoactive_pregnancy___1, psychoactive_pregnancy___2,
                          psychoactive_pregnancy___3, delivery, momlivebirths,
                          totalpregnancies, maternalproblems1, asd1, deaf1, ddfamily1,
                          szbpfamily1, risk_score_ASD) 
```



```{r}
# filter out age and live births outliers
predata <- predata %>% filter(momlivebirths != 10 & momsdeliveryage != 12 | momlivebirths != 10 & momsdeliveryage != 18)
summary(predata)
```

# Creating count variables for diff. drugs:

```{r}
# resulting columns are total number of trimesters drug was used
predata$tri_tobacco = rowSums(predata[,52:54])
predata$tri_vaping = rowSums(predata[,55:57])
predata$tri_alcohol = rowSums(predata[,58:60])
predata$tri_cannabis = rowSums(predata[,61:63])
predata$tri_stimulants = rowSums(predata[,64:66])
predata$tri_opioids = rowSums(predata[,67:69])
predata$tri_psychoactives = rowSums(predata[,70:72])

# getting rid of "when drug" columns
predata[,52:72] = NULL
```

# Remove mat_variable rows that occur after birth

```{r}
ifelse(cbdata$mat_adhd==3, NA, cbdata$mat_adhd)
ifelse(cbdata$mat_dep==3, NA, cbdata$mat_dep)
ifelse(cbdata$mat_anx==3, NA, cbdata$mat_anx)
ifelse(cbdata$mat_ocd==3, NA, cbdata$mat_ocd)
ifelse(cbdata$mat_bp==3, NA, cbdata$mat_bp)
ifelse(cbdata$mat_pssd==3, NA, cbdata$mat_pssd)
ifelse(cbdata$mat_other==3, NA, cbdata$mat_other)
```


