---
title: "141SL Autism"
author: "Rose Din (ID: 804764627), Lisa Kaunitz (ID: 404731988), Claire Markey (ID: 104789928), Allison Ocelo (ID: 404799327), Cristina Sanchez (ID: 805119924), and Kayla Schroeder (ID: 804729436) - Section 1A"
date: "2/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(readr)
ChatterBabyData <- read_csv("ChatterBabyData.csv")
```

```{r}
# Extract weight values
for (i in 1:nrow(data){
  extracted_values <- stringr::str_extract_all(as.character(data$babysweightlbs[i]),"[[:digit:]]+")
}
```


Cleaning/ Transforming the Data: 

- removing the `asdbehaviors` and `lostskillsdemographics` columns becuase they make up the outcome
- removing the baby language as a predictor 

```{r}
cbdata <- ChatterBabyData[,-c(1:7, 217:240)]
```



Transforming the weight from kg to pounds then cbind into the same column for lbs: 

```{r}
cbdata$weightkg <- as.numeric(cbdata$weightkg)
cbdata$weightkg <- 2.20462 * cbdata$weightkg
cbdata$babysweightlbs <- cbind(cbdata$babysweightlbs, cbdata$weightkg)

```

